version: '3'

services:
  bi-platform:
    image: metabase/metabase
    container_name: smc-blitar-metabase
    ports:
      - "4000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_PASSWORD_COMPLEXITY: normal
      JAVA_TIMEZONE: Asia/Jakarta
      MUID: 1000
      MGID: 1000
    restart: always
    volumes:
      - ./data/metabase-data:/metabase-data
